on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: CommunityPro
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<p><b>Invitation sent to join the Organisation</b></p> <b>Welcome to the community🎉 </b><br><br>Dont forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can read more on how to do that, <a href="https://github.com/CommunityPro/support#-how-to-make-the-organization-public">here</a>. <br>Tips for practising:<br>Now you are a member, add your profile to this practice repo, you can find instructions on how to add your name to the README <a href="">here</a><br><p>Remember contributing to open source is not just about code, its about collaboration, communication and adding value<br><b>Thank you and welcome to the community</b></p>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
